### ISSUE TITLE
generated projection missing t.timestamps

### ISSUE THREAD

**Issue by prognostikos** [fhwang/event_sourced_record#10]
Not sure if this is intentional or not, but the generated projection migration doesn't seem to include the standard `t.timestamps, null: false`

**Comment by fhwang** [comment]
Yeah, I guess I was thinking, since the projection is just a cache, the timestamps aren't very important. But do you think you might end up using them for something?

**Comment by prognostikos** [comment]
I will definitely use them when reading the projections - e.g.  `updated_at` being used for for fragment caching and http caching with `stale?`

But it's easy enough to add them to the migration myself, so no biggie if you don't want it in the gem.

**Comment by fhwang** [comment]
Makes sense, and there shouldn't be any harm in having them for those people who never use them. I'll add this in a bit.
