### ISSUE TITLE
Bootstrap existing model?

### ISSUE THREAD

**Issue by Trevoke** [fhwang/event_sourced_record#17]
If, instead of creating a new model with the gem, I modify an existing one, I am likely to end up with empty `uuid` attributes. They will likely need a `uuid` generated (this is not overly difficult, since you are just using `SecureRandom.uuid`).

I will probably want to be able to generate a `creation` event for these pre-existing objects. How can I do this?

**Comment by fhwang** [comment]
I'm not sure if there's a standard way of handling this problem, but in the past I've used a different kind of event, such as `legacy_conversion`. This reflects the fact that the projection existed before event sourcing was being used, and serves a useful marker that, even though we've made our best effort at preserving history, some of that history may have already been lost.

I find this is a useful distinction to make from a standard `creation`, which implies that you're looking at a record that has only lived under an event sourcing system and thus you should be able to be much more confident about the projection you're dealing with.

For `uuid` assignment, I'd probably try creating it manually on the model before making the event, for example:

```
subscription.update_attribute(:uuid, SecureRandom.uuid)
subscription.events.legacy_conversion.create!(
  bottles_per_shipment: subscription.bottles_per_shipment
)
```

Want to give that a try and let me know how that works out?

**Comment by fhwang** [comment]
I'm going to close this out for now, please feel free to re-open if you feel that's appropriate.
