### ISSUE TITLE
EventSourcedRecord::Event#respond_to? breaks if attributes are blank

### ISSUE THREAD

**Issue by tomciopp** [fhwang/event_sourced_record#18]
I believe this is an issue in EventSourcedRecord::Event::EventTypeConfig on line 13.

```
def attributes(*attrs)
  attrs.present? ? @attributes = attrs : @attributes
end
```

If there are no attributes when an event_type is instance eval'd the attrs variable will return an empty array. The empty array will return false when present? is called and it will return a nil @attributes. This causes an error in the following code EventSourcedRecord::Event#respond_to?

```
def respond_to?(meth, include_all = false)
  if event_type_config && event_type_config.attributes.include?(meth)
    true
  elsif event_type_config && event_type_config.attributes.any? { |a| "#{a}=" == meth }
    true
  else
    super
  end
end
```

Since the attributes are nil, a NoMethodError will be raised: `undefined method include? for nil:NilClass`

**Comment by fhwang** [comment]
Can you submit some example code that would demonstrate this bug? Thanks!

**Comment by tomciopp** [comment]
This will happen any time an event_type block does not specify an attributes method i.e.

```
class ExampleEvent < ActiveRecord::Base
  include EventSourcedRecord::Event
  serialize :data

  belongs_to :example, foreign_key: 'example_uuid', primary_key: 'uuid'

  event_type :creation do 
  end
end
```

If I try to do the following, it will raise the NoMethodError

```
example = FactoryGirl.create(:example)
ExampleEvent.create({
  "event_type" => "creation",
  "example_uuid" => example.uuid,
  "occurred_at" => Time.current,
  "data" => {}
})
```

If you need an example application I can create one that demonstrates this issue.

**Comment by fhwang** [comment]
That was enough to help me see the bug. Thanks!
